// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SkipTitle","status":false,"description":"v1.00 Skips Title Screen\r\n<SilverSkipTitle>","parameters":{"Skip Title Screen Entirely":"true","Skip If Savefile Present":"true","FadeOut Title":"false"}},
{"name":"SRD_CameraCore","status":true,"description":"Allows developers to preform various camera motions including focusing and zooming.","parameters":{"Default Zoom":"1","Zoom Pictures?":"true","Margin Formula":"(Graphics.width / scale) - Graphics.width","Fix Black Lines":"false"}},
{"name":"TacticsSystem","status":true,"description":"A Tactical Battle System like Final Fantasy Tactics or Fire Emblem series.","parameters":{"cursor speed":"2","grid opacity":"30","move points":"5","action range":"diamond 1","move scope color":"#0066CC","ally scope color":"#008000","enemy scope color":"#B22222","animationId of death":"97","show hp gauge":"1","show state icon":"1","show phase sprite":"1","duration phase sprite":"120","show information window":"1","text manager":"","player phase term":"Player Phase","enemy phase term":"Enemy Phase","damage term (abbr.)":"Dmg","hit rate term (abbr.)":"Hit","critical rate term (abbr.)":"Cri"}}
];
